# Generated by Django 2.2.6 on 2019-12-01 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('bairro', models.CharField(blank=True, max_length=255)),
                ('rua', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=255)),
                ('telefone_fixo', models.CharField(blank=True, max_length=255)),
                ('telefone_celular', models.CharField(blank=True, max_length=255)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grupo.Cidade')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_individual', models.BooleanField(default=False)),
                ('is_informal', models.BooleanField(default=False)),
                ('is_formal', models.BooleanField(default=False)),
                ('cadastro_individual_iniciado', models.BooleanField(default=False)),
                ('cadastro_individual_finalizado', models.BooleanField(default=False)),
                ('cadastro_formal_iniciado', models.BooleanField(default=False)),
                ('cadastro_formal_finalizado', models.BooleanField(default=False)),
                ('cadastro_informal_iniciado', models.BooleanField(default=False)),
                ('cadastro_informal_finalizado', models.BooleanField(default=False)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('entidade_formal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidade_formal', to='grupo.Entidade')),
                ('entidade_individual', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidade_individual', to='grupo.Entidade')),
                ('entidade_informal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidade_informal', to='grupo.Entidade')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('unidade', models.CharField(max_length=255)),
                ('validado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoSugerido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo.Produto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_grupo', models.PositiveSmallIntegerField()),
                ('quantidade', models.PositiveIntegerField()),
                ('sazonalidade_janeiro', models.BooleanField(default=False, help_text='Janeiro')),
                ('sazonalidade_fevereiro', models.BooleanField(default=False, help_text='Fevereiro')),
                ('sazonalidade_marco', models.BooleanField(default=False, help_text='Março')),
                ('sazonalidade_abril', models.BooleanField(default=False, help_text='Abril')),
                ('sazonalidade_maio', models.BooleanField(default=False, help_text='Maio')),
                ('sazonalidade_junho', models.BooleanField(default=False, help_text='Junho')),
                ('sazonalidade_julho', models.BooleanField(default=False, help_text='Julho')),
                ('sazonalidade_agosto', models.BooleanField(default=False, help_text='Agosto')),
                ('sazonalidade_setembro', models.BooleanField(default=False, help_text='Setembro')),
                ('sazonalidade_outubro', models.BooleanField(default=False, help_text='Outubro')),
                ('sazonalidade_novembro', models.BooleanField(default=False, help_text='Novembro')),
                ('sazonalidade_dezembro', models.BooleanField(default=False, help_text='Dezembro')),
                ('validado', models.BooleanField(default=False)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo.Grupo')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo.Entidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipanteGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_grupo', models.PositiveSmallIntegerField()),
                ('validado', models.BooleanField(default=False)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='grupo.Grupo')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participante_grupo', to='grupo.Entidade')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoInformal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade_articulada', models.CharField(blank=True, max_length=255, null=True)),
                ('reconhecimento_economia_solidaria', models.BooleanField()),
                ('ano_formacao', models.PositiveSmallIntegerField()),
                ('reconhecimento_indigena', models.BooleanField()),
                ('reconhecimento_quilombola', models.BooleanField()),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grupo.Grupo')),
            ],
            options={
                'verbose_name_plural': 'Grupos Informais',
                'verbose_name': 'Grupo Informal',
            },
        ),
        migrations.CreateModel(
            name='GrupoIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dap_fisica', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grupo.Grupo')),
            ],
            options={
                'verbose_name_plural': 'Grupos Individuais',
                'verbose_name': 'Grupo Individual',
            },
        ),
        migrations.CreateModel(
            name='GrupoFormal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dap_juridica', models.CharField(max_length=255, unique=True)),
                ('ano_fundacao', models.PositiveSmallIntegerField()),
                ('tipo_formal', models.CharField(choices=[('AS', 'Associação'), ('CO', 'Cooperativa'), ('N', 'Não Informado')], default='N', max_length=2)),
                ('reconhecimento_economia_solidaria', models.BooleanField()),
                ('reconhecimento_indigena', models.BooleanField()),
                ('reconhecimento_quilombola', models.BooleanField()),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('data_atualizado', models.DateTimeField(auto_now=True)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grupo.Grupo')),
                ('representante_legal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grupo.Entidade')),
            ],
            options={
                'verbose_name_plural': 'Grupos Formais',
                'verbose_name': 'Grupo Formal',
            },
        ),
        migrations.CreateModel(
            name='EntidadeJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('entidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grupo.Entidade')),
            ],
        ),
        migrations.CreateModel(
            name='EntidadeFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Desconhecido')], default='N', max_length=1)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(help_text='Sem pontos e traço, apenas números.', max_length=11, unique=True)),
                ('entidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grupo.Entidade')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo.Uf'),
        ),
    ]
