# Generated by Django 2.2.1 on 2019-12-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='telefone_celular',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='grupoindividual',
            name='dap_fisica',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
